#!/bin/bash
########################################################################
# Copyright (c) 1988-2022 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: sony-soundbar
#
# Author: $author$
#   Date: 10/19/2022
#
# sony soundbar utility script
########################################################################
dirname=`dirname $0`
basename=`basename $0`

title='sony soundbar utility script'
utility=$dirname'/../build/sony'
creds=$dirname'/../creds/build/sony'

default_host=`$creds/sony-soundbar-host`

if [ "$1" != "" ]; then
    if [ "$2" != "" ]; then
    host=$1
    else # [ "$2" != "" ]; then
    host=$default_host
    fi # [ "$2" != "" ]; then
else # [ "$1" != "" ]; then
host=$default_host
fi # [ "$1" != "" ]; then

if [ "$1" != "" ]; then
    if [ "$2" != "" ]; then
    $utility -o$host $2 $3 $4
    else # [ "$2" != "" ]; then
    $utility -o$host $1 $2 $3 $4
    fi # [ "$2" != "" ]; then
else # [ "$1" != "" ]; then
echo
echo $title
echo
echo usage `basename $0` '[hostname['$host'(`sony-soundbar-host`)]]' '...' '(-h or --help -- options)'
fi # [ "$1" != "" ]; then
