#!/bin/bash
########################################################################
# Copyright (c) 1988-2021 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: evu-cp
#
# Author: $author$
#   Date: 10/9/2021
#
# evupit utility script
########################################################################
dirname=`dirname $0`
basename=`basename $0`

source='source'
target='target'
directory='directory'
utility='evupit-cp'

if [ "$1" != "" ]; then
source=$1
fi # [ "$1" != "" ]; then

if [ "$2" != "" ]; then
target=$2
fi # [ "$2" != "" ]; then

if [ "$3" != "" ]; then
directory=$3
fi # [ "$3" != "" ]; then

if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
echo $utility $source'/'$directory $target'/'$directory $4 $5 $6 $7 $8 $9 ...
$utility $source'/'$directory $target'/'$directory $4 $5 $6 $7 $8 $9
echo ... $utility $source'/'$directory $target'/'$directory $4 $5 $6 $7 $8 $9
else # [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
echo
echo usage $basename 'source' 'target' 'directory' '...'
echo
echo $utility 'source/directory' 'target/directory' '$4 $5 $6 $7 $8 $9'
echo
fi # [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
