#!/bin/bash
########################################################################
# Copyright (c) 1988-2022 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: evu-all
#
# Author: $author$
#   Date: 9/6/2022
########################################################################
dirname=`dirname $0`
basename=`basename $0`

match=`$dirname/evupdate-match-all`
skip=`$dirname/evupdate-skip`

if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
echo $dirname/evu $1 $2 $3 -m'"'$match'"' -k'"'$skip'"' $4 $5 $6 ...
$dirname/evu $1 $2 $3 -m$match -k$skip $4 $5 $6
echo ... $dirname/evu $1 $2 $3 -m'"'$match'"' -k'"'$skip'"' $4 $5 $6
else # [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
echo
echo usage $basename source target directory
echo '$dirname/evu' '$1' '$2' '$3' '-m$match' '-k$skip' '...'
echo
echo '$match="'$match'"'
echo
echo '$skip="'$skip'"'
echo
fi # [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
