#!/bin/bash
########################################################################
# Copyright (c) 1988-2021 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: evup-all
#
# Author: $author$
#   Date: 3/31/2021
#
# evupdate utility script
########################################################################
dirname=`dirname $0`
basename=`basename $0`

match=`$dirname/evupdate-match-all`
skip=`$dirname/evupdate-skip`

if [ "$1" != "" ] && [ "$2" != "" ]; then
$dirname/evupdate -p -m"$match" -k"$skip" $1 $2 $3 $4 $5 $6 $7 $8 $9
else
echo
echo evupdate utility script
echo
echo usage `basename $0` sourcedir targetdir
echo '$dirname/evupdate' -p -m'"`$dirname/evupdate-match-all`"' -k'"`$dirname/evupdate-skip`"' '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'
echo
echo '`$dirname/evupdate-match-all`'='"'$match'"'
echo
echo '`$dirname/evupdate-skip`'='"'$skip'"'
fi
